// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SafeShare.DataAccessLayer.Context;

#nullable disable

namespace SafeShare.DataAccessLayer.Migrations.CryptoKeysDbMigrations
{
    [DbContext(typeof(CryptoKeysDb))]
    [Migration("20240110095204_InitialCreationDbCryptoKeys")]
    partial class InitialCreationDbCryptoKeys
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SafeShare.DataAccessLayer.Models.SafeShareApi.CryptoModels.GroupKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uniqueidentifier");

                    b.Property<string>("CryptoKey")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<Guid>("GroupId")
                        .HasColumnType("uniqueidentifier");

                    b.Property<DateTime>("KeyCreatedTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("KeyUpdatedTime")
                        .HasColumnType("datetime2");

                    b.HasKey("Id");

                    b.ToTable("GroupKeys");
                });
#pragma warning restore 612, 618
        }
    }
}
